pipeline {
    agent {
        docker {
      label 'al2'
      image 'cypress/browsers:node18.12.0-chrome107'
      args '--ipc=host'
    }
    }
     parameters{
        choice(name: 'POJECTS', choices: ['stratasphere', 'arfp'], description: "Choice the Project to run")
    }
     options{
        ansiColor('xterm')
    }
    stages {
        stage('Test') {
            steps {
                sh "cd E2E/ARFP-Stratasphere && npm cache clean --force && npm ci --prefer-offline && npx cypress run --browser chrome --headed --env tags=\"@${POJECTS}\""
            }
        }
    }

    post{
        always{
            publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'cypress/reports', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: '', useWrapperFileDirectly: true])
        }
    }

    // post {
    //     always{
    //                echo 'Testing Completed!'
    //     script {
    //         sh "node ./cucumber-html-report.js"
    //     } 
    //     }

    //     }

    }

    